-- Superseded by 20260323000003_add_password_management_fields.
-- OTP-based reset (otpHash, otpExpiresAt, otpResetToken, otpResetTokenExp) was removed.
-- mustChangePassword and passwordChangedAt are now handled in the later migration.
-- This file is kept as a placeholder to preserve migration history ordering.